# Generated by Django 5.0.4 on 2024-05-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Coustomer Support', 'Coustomer Support'), ('Python developer', 'Python developer')], max_length=50)),
                ('emp_id', models.CharField(max_length=10)),
                ('profile', models.ImageField(upload_to='profile/employees/')),
                ('designation', models.CharField(max_length=6)),
                ('description', models.TextField()),
                ('docs', models.FileField(upload_to='employes/documents/')),
            ],
        ),
    ]
