# Generated by Django 5.0.4 on 2024-05-10 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employ',
            name='docs',
        ),
    ]
