# Generated by Django 5.0.4 on 2024-05-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0002_remove_employ_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employ',
            name='description',
            field=models.CharField(max_length=5000),
        ),
    ]
