# Generated by Django 5.0.4 on 2024-05-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0003_alter_employ_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employ',
        ),
    ]
