# Generated by Django 5.0.4 on 2024-05-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customersupport',
            old_name='_from',
            new_name='by_from',
        ),
    ]
