# Generated by Django 5.0.4 on 2024-05-23 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_messsanger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='messsanger',
        ),
    ]
