# Generated by Django 5.0.4 on 2024-05-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_delete_messsanger'),
    ]

    operations = [
        migrations.CreateModel(
            name='messsanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('msg', models.TextField()),
                ('sender_id', models.CharField(max_length=11)),
                ('sender_type', models.CharField(max_length=10)),
                ('created', models.CharField(max_length=6)),
            ],
        ),
    ]
