# Generated by Django 5.0.4 on 2024-04-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_remove_college_postal_code_alter_college_university'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
