# Generated by Django 5.0.4 on 2024-04-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Clang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='CPPlang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DBMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='GOlang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='HTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Java',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='JavaScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='PHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rlang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RUST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='SWIFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
            ],
        ),
    ]
