# Generated by Django 5.0.4 on 2024-04-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_chash_clang_cpplang_dbms_golang_html_java_javascript_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chash',
        ),
        migrations.DeleteModel(
            name='Clang',
        ),
        migrations.DeleteModel(
            name='College',
        ),
        migrations.DeleteModel(
            name='CPPlang',
        ),
        migrations.DeleteModel(
            name='DBMS',
        ),
        migrations.DeleteModel(
            name='GOlang',
        ),
        migrations.DeleteModel(
            name='HTML',
        ),
        migrations.DeleteModel(
            name='Java',
        ),
        migrations.DeleteModel(
            name='JavaScript',
        ),
        migrations.DeleteModel(
            name='PHP',
        ),
        migrations.DeleteModel(
            name='Python',
        ),
        migrations.DeleteModel(
            name='Rlang',
        ),
        migrations.DeleteModel(
            name='RUST',
        ),
        migrations.DeleteModel(
            name='SWIFT',
        ),
    ]
