# Generated by Django 5.0.4 on 2024-04-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college', '0011_delete_chash_delete_clang_delete_college_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Clang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('university', models.CharField(choices=[('SVUTPT', 'Sri Venkataswara University , Tirupati'), ('APUVIZ', 'Andra University ,  Visakhapatnam')], max_length=6)),
                ('clg_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=54)),
                ('postal', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CPPlang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DBMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GOlang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HTML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Java',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JavaScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rlang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RUST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SWIFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=12)),
                ('test', models.CharField(max_length=5)),
                ('payment', models.CharField(max_length=5)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
