# Generated by Django 5.0.4 on 2024-04-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0012_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chash',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clang',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cpplang',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dbms',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='golang',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='html',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='java',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='javascript',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='php',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='python',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rlang',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rust',
            name='payment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='swift',
            name='payment',
            field=models.CharField(max_length=50),
        ),
    ]
