# Generated by Django 5.0.4 on 2024-04-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0019_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chash',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clang',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cpplang',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='dbms',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='golang',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='html',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='java',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='javascript',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='php',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='python',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rlang',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rust',
            name='test',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='swift',
            name='test',
            field=models.IntegerField(),
        ),
    ]
