# Generated by Django 5.0.4 on 2024-05-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0022_chash_clang_cpplang_dbms_golang_html_java_javascript_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
