# Generated by Django 5.0.4 on 2024-05-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0024_college'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chash',
        ),
        migrations.DeleteModel(
            name='Clang',
        ),
        migrations.DeleteModel(
            name='CPPlang',
        ),
        migrations.DeleteModel(
            name='DBMS',
        ),
        migrations.DeleteModel(
            name='GOlang',
        ),
        migrations.DeleteModel(
            name='HTML',
        ),
        migrations.DeleteModel(
            name='Java',
        ),
        migrations.DeleteModel(
            name='JavaScript',
        ),
        migrations.DeleteModel(
            name='PHP',
        ),
        migrations.DeleteModel(
            name='Python',
        ),
        migrations.DeleteModel(
            name='Rlang',
        ),
        migrations.DeleteModel(
            name='RUST',
        ),
        migrations.DeleteModel(
            name='SWIFT',
        ),
    ]
