# Generated by Django 5.0.4 on 2024-05-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0026_chash_clang_cpplang_dbms_golang_html_java_javascript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='profile',
            field=models.ImageField(upload_to='profile/college/'),
        ),
    ]
