# Generated by Django 5.0.4 on 2024-04-15 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
