# Generated by Django 5.0.4 on 2024-04-16 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
