# Generated by Django 5.0.4 on 2024-04-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='test_code',
        ),
    ]
