# Generated by Django 5.0.4 on 2024-04-25 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_student_test_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
