# Generated by Django 5.0.4 on 2024-04-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
