# Generated by Django 5.0.4 on 2024-04-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_rename_field_name_student_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='terms',
            field=models.CharField(max_length=6),
        ),
    ]
