# Generated by Django 5.0.4 on 2024-05-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_student_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
