# Generated by Django 5.0.4 on 2024-05-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
