# Generated by Django 5.0.4 on 2024-04-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qusetion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.CharField(max_length=250)),
                ('a', models.CharField(max_length=250)),
                ('b', models.CharField(max_length=50)),
                ('c', models.CharField(max_length=250)),
                ('d', models.CharField(max_length=250)),
                ('ans', models.CharField(max_length=1)),
                ('uni', models.CharField(max_length=6)),
                ('clg', models.CharField(max_length=10)),
                ('sub', models.CharField(choices=[('PY', 'Python'), ('JAVA', 'Java'), ('C', 'C Lanaguage'), ('Cpp', 'C++ Lanaguage')], max_length=6)),
            ],
        ),
    ]
