# Generated by Django 5.0.4 on 2024-04-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_rename_problem_qusetion_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qusetion',
            old_name='name',
            new_name='problem',
        ),
    ]
