# Generated by Django 5.0.4 on 2024-04-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_rename_name_qusetion_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qusetion',
            name='sub',
            field=models.CharField(choices=[('PY', 'Python'), ('JAVA', 'Java'), ('C', 'C Lanaguage'), ('CPP', 'C++ Lanaguage'), ('DBMS', 'Data Base Manaagement System'), ('PHP', 'PHP'), ('HTML', 'HTML'), ('JS', 'Java Script'), ('R', 'R language'), ('C#', 'C hash'), ('GO', 'GO Lanaguage'), ('SWIFT', 'SWIFT Lanaguage'), ('RUST', 'RUST Lanaguage')], max_length=5),
        ),
    ]
