# Generated by Django 5.0.4 on 2024-04-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_qusetion_sub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qusetion',
            new_name='Question',
        ),
    ]
