# Generated by Django 5.0.4 on 2024-05-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_rename_qusetion_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='University',
        ),
    ]
