# Generated by Django 5.0.4 on 2024-05-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_delete_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('uni', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=54)),
                ('postal', models.CharField(max_length=254)),
                ('profile', models.ImageField(upload_to='profile/university/')),
            ],
        ),
    ]
